version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
    networks:
      - hutieugo-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hutieugo
      MYSQL_USER: Qi
      MYSQL_PASSWORD: 040104
    ports:
      - "3306:3306"
    networks:
      - hutieugo-network

  backend:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`hutieugo.id.vn`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hutieugo
      SPRING_DATASOURCE_USERNAME: Qi
      SPRING_DATASOURCE_PASSWORD: 040104
    depends_on:
      - mysql
    networks:
      - hutieugo-network

  frontend:
    image: frontend-hutieugo_frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.hutieugo.id.vn`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
    networks:
      - hutieugo-network

networks:
  hutieugo-network:
    driver: bridge
